-- =============================================================================
-- Batch 1: AGA-certified farms (directory seed)
-- Run in Supabase SQL Editor once. These rows have NO auth users — profiles are
-- not created (same pattern as listing-only farms you add manually).
--
-- Optional: add cert_verified_at / cert_verified_by / reviewed_by via migrations if you use them;
-- this seed only sets columns common to a minimal farms table + cert_type.
--
-- Mapping notes:
-- - Half Moon Bay: ZIP not in source; used 94019.
-- - Greenfield, IN: ZIP corrected from 46410 to 46140 (Greenfield).
-- - Shannon (Leafy Creek): no email in paste — used info@glranch.com (verify).
-- - Crawley's: no contact in paste — placeholder email/phone (replace).
-- - Richard Field: "Website" line in source was an email; website left null.
-- =============================================================================

INSERT INTO farms (
  name,
  contact_name,
  contact_email,
  contact_phone,
  website,
  address,
  city,
  state,
  zip,
  description,
  livestock_types,
  produce_types,
  regenerative_practices,
  certifications,
  cert_type,
  cert_other,
  cert_file_url,
  status,
  approved_at,
  updated_at
) VALUES
  (
    'Canyon Meadows Ranch',
    'Kendall & Lori Curtis',
    'loricurtis987@gmail.com',
    '719-252-5973',
    'http://www.curtisranch.net/',
    '8387 Cuerva Verda Rd',
    'Rye',
    'CO',
    '81069',
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Curtis Ranch',
    'Bill West',
    'brwest74@gmail.com',
    '229-378-7673',
    NULL,
    '200 Grady Ranch Lane',
    'Whigham',
    'GA',
    '39897',
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Grady Ranch',
    'Jake Pettit',
    'pettitpastures@gmail.com',
    '612-401-6872',
    NULL,
    '9341 125th Ave',
    'Milaca',
    'MN',
    '56353',
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Pettit Pastures',
    'Doniga Markegard',
    'info@markegardfamily.com',
    '650-670-7984',
    NULL,
    '20080 Cabrillo Hwy S',
    'Half Moon Bay',
    'CA',
    '94019',
    'Grass-fed beef. American Grassfed Association (AGA) certified. (ZIP inferred; verify address.)',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Markegard Family Grass-Fed',
    'Carrie Richards',
    'carrie@richardsgrassfedbeef.com',
    '(510) 390-4707',
    NULL,
    'PO Box 145',
    'Oregon House',
    'CA',
    '95962',
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Richards Grassfed Beef',
    'Cynthia Houseweart',
    'CynthRanch@aol.com',
    '970-872-2144',
    NULL,
    '32282 J Road',
    'Hotchkiss',
    'CO',
    '81419',
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Left Coast Grassfed',
    'Kathy Webster',
    'info@leftcoastgrassfed.com',
    '650-879-2147',
    NULL,
    '2997 Pescadero Creek Road',
    'Pescadero',
    'CA',
    '94060',
    'Grass-fed beef. Listed as Princess Beef in source; named from Left Coast Grassfed contact. American Grassfed Association (AGA) certified.',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Leafy Creek Farm LLC',
    'Shannon Gonsoulin',
    'info@glranch.com',
    '337-577-9162',
    'http://www.glranch.com',
    '6108 Loreauville Rd',
    'New Iberia',
    'LA',
    '70563',
    'Grass-fed beef. American Grassfed Association (AGA) certified. Email guessed from Gonsoulin site — verify.',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Gonsoulin Land and Cattle, LLC',
    'Margaret Buchanan',
    'margaret@flyingbbar.com',
    '303-887-9735',
    'https://www.flyingbbar.com/',
    '7300 Yulle Road',
    'Strasburg',
    'CO',
    '80136',
    'Grass-fed beef. Flying B Bar / Gonsoulin. American Grassfed Association (AGA) certified.',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Field''s Grassfed Beef, LLC',
    'Richard Field',
    'fieldbeef@gmail.com',
    '541-820-4430',
    NULL,
    '29500 N River Rd',
    'Prairie City',
    'OR',
    '97869',
    'Grass-fed beef. Source labeled Website with email; website URL not provided. American Grassfed Association (AGA) certified.',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Caitlyn Farms Sustainably Raised Beef',
    'Atley Elliott',
    'atleyelliott@gmail.com',
    '828-407-7029',
    'https://beefandbobwhites.com/',
    '1507 Toney Road',
    'Mill Spring',
    'NC',
    '28756',
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Crawley''s Country Beef, LLC',
    'Office',
    'bulk-import+crawleys@placeholder.local',
    '000-000-0000',
    NULL,
    '3450 Big Bear Drive',
    'Sedalia',
    'CO',
    '80135',
    'Grass-fed beef. No phone/email in source — REPLACE contact fields. American Grassfed Association (AGA) certified.',
    '["Beef"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  ),
  (
    'Kiana Creek Ranch',
    'Amber Groce',
    'amber@farmersmarket.com',
    '317-477-7940',
    'https://www.tynerpondfarm.com',
    '7408 E 200 S',
    'Greenfield',
    'IN',
    '46140',
    'Grass-fed beef and pork. Tyner Pond Farm / Kiana Creek Ranch. American Grassfed Association (AGA) certified. (ZIP corrected to 46140 for Greenfield, IN.)',
    '["Beef","Pork"]',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'aga',
    NULL,
    NULL,
    'approved',
    now(),
    now()
  );
