INSERT INTO farms (
  name,
  contact_name,
  contact_email,
  contact_phone,
  website,
  address,
  city,
  state,
  zip,
  description,
  livestock_types,
  produce_types,
  regenerative_practices,
  certifications,
  status,
  approved_at,
  updated_at
) VALUES
  (
    'Curtis Ranch',
    'Kendall & Lori Curtis',
    'loricurtis987@gmail.com',
    '719-252-5973',
    'http://www.curtisranch.net/',
    '8387 cuerva verda rd',
    'Rye',
    'CO',
    '81069',
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    'Beef',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'approved',
    now(),
    now()
  ),
  (
    'Grady Ranch',
    'Bill West',
    'brwest74@gmail.com',
    '229-378-7673',
    NULL,
    '200 Grady Ranch Lane',
    'Whigham',
    'GA',
    '39897',
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    'Beef',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'approved',
    now(),
    now()
  ),
  (
    'Pettit Pastures',
    'Jake Pettit',
    'pettitpastures@gmail.com',
    '612-401-6872',
    NULL,
    '9341 125th Ave',
    'Milaca',
    'MN',
    '56353',
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    'Beef',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'approved',
    now(),
    now()
  ),
  (
    'Markegard Family Grass-Fed / Markegard Family Farm',
    'Doniga Markegard',
    'info@markegardfamily.com',
    '650-670-7984',
    NULL,
    '20080 cabrijo highway S',
    'Half Moon Bay',
    'CA',
    NULL,
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    'Beef',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'approved',
    now(),
    now()
  ),
  (
    'Princess Beef',
    'Cynthia Houseweart',
    'CynthRanch@aol.com',
    '970-872-2144',
    NULL,
    '32282 J Road',
    'Hotchkiss',
    'CO',
    '81419',
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    'Beef',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'approved',
    now(),
    now()
  ),
  (
    'Leafy Creek Farm LLC',
    'Kathy Webster',
    'info@leftcoastgrassfed.com',
    '650-879-2147',
    NULL,
    '2997 Pescadero Creek Road',
    'Pescadero',
    'CA',
    '94060',
    'Grass-fed beef. American Grassfed Association (AGA) certified.',
    'Beef',
    NULL,
    NULL,
    'American Grassfed Association (AGA)',
    'approved',
    now(),
    now()
  );
